-- CareNest administrator governance. Run AFTER admin-verification-migration.sql
-- Safe to re-run. No service-role key is required by the application.

alter table public.profiles
  add column if not exists account_status text not null default 'active',
  add column if not exists suspended_at timestamptz,
  add column if not exists suspended_reason text;

alter table public.medical_records
  add column if not exists file_size bigint,
  add column if not exists processing_status text not null default 'not_requested';

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_role text not null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  ip_address text,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);

create table if not exists public.app_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.app_settings(setting_key,setting_value) values
 ('max_upload_bytes','5242880'::jsonb),
 ('allowed_upload_types','["application/pdf","image/jpeg","image/png","image/webp"]'::jsonb)
on conflict (setting_key) do nothing;

create table if not exists public.specializations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.carenest_is_active_account()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and account_status='active');
$$;

create or replace function public.carenest_audit(
  event_action text, target_kind text, target_value text default null, event_details jsonb default '{}'::jsonb
) returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.carenest_is_admin() then raise exception 'Administrator access is required'; end if;
  insert into public.audit_logs(actor_id,actor_role,action,target_type,target_id,details)
  values(auth.uid(),'admin',event_action,target_kind,target_value,coalesce(event_details,'{}'::jsonb));
end;
$$;

create or replace function public.carenest_set_account_status(
  target_user uuid, next_status text, reason text default null
) returns void language plpgsql security definer set search_path=public as $$
declare admins integer;
begin
  if not public.carenest_is_admin() then raise exception 'Administrator access is required'; end if;
  if next_status not in ('active','suspended') then raise exception 'Invalid account status'; end if;
  if target_user=auth.uid() then raise exception 'You cannot suspend or reactivate your own administrator account'; end if;
  select count(*) into admins from public.profiles where role='admin' and account_status='active';
  if (select role from public.profiles where id=target_user)='admin' and next_status='suspended' and admins <= 1 then
    raise exception 'The last active administrator cannot be suspended';
  end if;
  update public.profiles set account_status=next_status,
    suspended_at=case when next_status='suspended' then now() else null end,
    suspended_reason=case when next_status='suspended' then nullif(trim(reason),'') else null end
    where id=target_user;
  perform public.carenest_audit('account_'||next_status,'profile',target_user::text,jsonb_build_object('reason',nullif(trim(reason),'')));
end;
$$;

create or replace function public.carenest_set_doctor_verification(
  target_doctor uuid, next_status text, review_reason text default null
) returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.carenest_is_admin() then raise exception 'Administrator access is required'; end if;
  if next_status not in ('verification_required','pending','under_review','verified','rejected') then raise exception 'Invalid verification status'; end if;
  if not exists(select 1 from public.profiles where id=target_doctor and role='doctor') then raise exception 'Doctor profile was not found'; end if;
  update public.profiles set verification_status=next_status, verification_reason=nullif(trim(review_reason),''), verification_reviewed_by=auth.uid(), verification_updated_at=now() where id=target_doctor;
  insert into public.notifications(user_id,type,title,body)
  values(target_doctor,'verification_' || next_status,'Credential review update','Your clinician verification status is now ' || replace(next_status,'_',' ') || coalesce(': ' || nullif(trim(review_reason),''),'.'));
  perform public.carenest_audit('doctor_verification_' || next_status,'profile',target_doctor::text,jsonb_build_object('reason',nullif(trim(review_reason),'')));
end;
$$;

create or replace function public.carenest_admin_announcement(
  target_user uuid, audience text, announcement_title text, announcement_body text
) returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.carenest_is_admin() then raise exception 'Administrator access is required'; end if;
  if char_length(trim(announcement_title)) < 2 or char_length(trim(announcement_body)) < 2 then raise exception 'Announcement title and message are required'; end if;
  if audience='specific' then
    if target_user is null then raise exception 'Choose a recipient'; end if;
    insert into public.notifications(user_id,type,title,body) values(target_user,'announcement',trim(announcement_title),trim(announcement_body));
  elsif audience in ('patients','doctors') then
    insert into public.notifications(user_id,type,title,body)
    select id,'announcement',trim(announcement_title),trim(announcement_body) from public.profiles where role=case when audience='patients' then 'patient' else 'doctor' end and account_status='active';
  else raise exception 'Invalid audience'; end if;
  perform public.carenest_audit('announcement_sent','notification',null,jsonb_build_object('audience',audience,'title',trim(announcement_title)));
end;
$$;

-- Admins may see administrative metadata, but never medical-record contents.
alter table public.audit_logs enable row level security;
alter table public.app_settings enable row level security;
alter table public.specializations enable row level security;
drop policy if exists admin_audit_read on public.audit_logs;
drop policy if exists admin_settings_manage on public.app_settings;
drop policy if exists admin_specializations_manage on public.specializations;
drop policy if exists admin_profiles_read on public.profiles;
drop policy if exists admin_appointments_read on public.appointments;
drop policy if exists admin_records_metadata on public.medical_records;
create policy admin_audit_read on public.audit_logs for select to authenticated using (public.carenest_is_admin());
create policy admin_settings_manage on public.app_settings for all to authenticated using (public.carenest_is_admin()) with check (public.carenest_is_admin());
create policy admin_specializations_manage on public.specializations for all to authenticated using (public.carenest_is_admin()) with check (public.carenest_is_admin());
create policy admin_profiles_read on public.profiles for select to authenticated using (public.carenest_is_admin());
create policy admin_appointments_read on public.appointments for select to authenticated using (public.carenest_is_admin());
create policy admin_records_metadata on public.medical_records for select to authenticated using (public.carenest_is_admin());

revoke insert, update, delete on public.audit_logs from authenticated;
revoke all on function public.carenest_audit(text,text,text,jsonb) from public;
revoke all on function public.carenest_set_account_status(uuid,text,text) from public;
revoke all on function public.carenest_admin_announcement(uuid,text,text,text) from public;
revoke all on function public.carenest_set_doctor_verification(uuid,text,text) from public;
grant execute on function public.carenest_is_active_account() to authenticated;
grant execute on function public.carenest_audit(text,text,text,jsonb) to authenticated;
grant execute on function public.carenest_set_account_status(uuid,text,text) to authenticated;
grant execute on function public.carenest_admin_announcement(uuid,text,text,text) to authenticated;
grant execute on function public.carenest_set_doctor_verification(uuid,text,text) to authenticated;
