-- CareNest appointment requests and in-app notifications. Safe to re-run.
-- This migration is self-contained and supports the original bigint appointments table.

alter table public.appointments
  add column if not exists doctor_id uuid references public.profiles(id) on delete set null,
  add column if not exists scheduled_at timestamptz,
  add column if not exists requested_at timestamptz not null default now(),
  add column if not exists response_note text,
  add column if not exists updated_at timestamptz not null default now();

update public.appointments
set scheduled_at = (appointment_date + coalesce(appointment_time, time '09:00')) at time zone 'Asia/Kolkata'
where scheduled_at is null and appointment_date is not null;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  related_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_unread_idx
  on public.notifications(user_id, read_at, created_at desc);

alter table public.notifications enable row level security;
drop policy if exists notifications_select_own on public.notifications;
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_select_own on public.notifications
  for select to authenticated using (user_id = auth.uid());
create policy notifications_update_own on public.notifications
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

alter table public.appointments drop constraint if exists appointments_status_check;
alter table public.appointments add constraint appointments_status_check
  check (status in ('pending','confirmed','proposed','rejected','cancelled','completed','scheduled'));

grant select, insert, update on public.appointments to authenticated;
grant select, update on public.notifications to authenticated;

create or replace function public.carenest_request_appointment(
  target_doctor uuid, preferred_at timestamptz, request_reason text
) returns bigint language plpgsql security definer set search_path=public as $$
declare appointment_id bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if preferred_at < now() then raise exception 'Choose a future date and time'; end if;
  if char_length(trim(coalesce(request_reason,''))) > 1000 then raise exception 'Reason is too long'; end if;
  if not exists (select 1 from public.profiles where id=target_doctor and role='doctor' and verification_status='verified') then
    raise exception 'This doctor is not available for appointments';
  end if;
  insert into public.appointments(patient_id,doctor_id,scheduled_at,reason,status,requested_at,updated_at)
  values(auth.uid(),target_doctor,preferred_at,nullif(trim(request_reason),''),'pending',now(),now()) returning id into appointment_id;
  insert into public.notifications(user_id,type,title,body,related_id)
  values(target_doctor,'appointment_request','New appointment request','A patient requested an appointment.',appointment_id)
  on conflict do nothing;
  return appointment_id;
end;
$$;

create or replace function public.carenest_review_appointment(
  target_appointment bigint, next_status text, scheduled_for timestamptz, reviewer_note text default null
) returns void language plpgsql security definer set search_path=public as $$
declare patient uuid; doctor uuid;
begin
  select patient_id,doctor_id into patient,doctor from public.appointments where id=target_appointment for update;
  if doctor is null or doctor <> auth.uid() then raise exception 'You cannot update this appointment'; end if;
  if next_status not in ('confirmed','proposed','rejected') then raise exception 'Invalid appointment decision'; end if;
  if next_status in ('confirmed','proposed') and scheduled_for < now() then raise exception 'Choose a future date and time'; end if;
  update public.appointments set status=next_status, scheduled_at=coalesce(scheduled_for,scheduled_at), response_note=nullif(trim(reviewer_note),''), updated_at=now() where id=target_appointment;
  insert into public.notifications(user_id,type,title,body,related_id)
  values(patient,'appointment_' || next_status,
    case next_status when 'confirmed' then 'Appointment confirmed' when 'proposed' then 'Appointment time updated' else 'Appointment declined' end,
    case next_status when 'confirmed' then 'Your appointment has been confirmed.' when 'proposed' then 'Your doctor proposed a new appointment time.' else 'Your doctor was unable to accept this appointment request.' end,
    target_appointment) on conflict do nothing;
end;
$$;

revoke all on function public.carenest_request_appointment(uuid,timestamptz,text) from public;
revoke all on function public.carenest_review_appointment(bigint,text,timestamptz,text) from public;
grant execute on function public.carenest_request_appointment(uuid,timestamptz,text) to authenticated;
grant execute on function public.carenest_review_appointment(bigint,text,timestamptz,text) to authenticated;
