-- CareNest clinician portal: run once in Supabase SQL Editor.
-- Safe to re-run: every schema change is guarded where possible.

alter table public.appointments
  add column if not exists doctor_id uuid references public.profiles(id) on delete set null;

create table if not exists public.doctor_notes (
  id bigint generated by default as identity primary key,
  doctor_id uuid not null references public.profiles(id) on delete cascade,
  patient_id uuid not null references public.profiles(id) on delete cascade,
  diagnosis text,
  treatment_plan text,
  note_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists doctor_notes_patient_created_idx
  on public.doctor_notes (patient_id, created_at desc);

grant select, insert, update, delete on public.doctor_notes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- A doctor is allowed only where a patient has an active, non-expired share.
create or replace function public.carenest_can_access_patient(target_patient_id uuid)
returns boolean
language sql stable security definer set search_path = public as $$
  select auth.uid() = target_patient_id
     or exists (
       select 1 from public.record_sharing s
       where s.patient_id = target_patient_id
         and s.doctor_id = auth.uid()
         and coalesce(s.status, 'active') = 'active'
         and (s.expires_at is null or s.expires_at > now())
     );
$$;

grant execute on function public.carenest_can_access_patient(uuid) to authenticated;

alter table public.doctor_notes enable row level security;
drop policy if exists care_nest_doctor_notes_read on public.doctor_notes;
drop policy if exists care_nest_doctor_notes_insert on public.doctor_notes;
drop policy if exists care_nest_doctor_notes_change on public.doctor_notes;
create policy care_nest_doctor_notes_read on public.doctor_notes for select to authenticated
  using (patient_id = auth.uid() or doctor_id = auth.uid());
create policy care_nest_doctor_notes_insert on public.doctor_notes for insert to authenticated
  with check (
    doctor_id = auth.uid()
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'doctor')
    and public.carenest_can_access_patient(patient_id)
  );
create policy care_nest_doctor_notes_change on public.doctor_notes for update to authenticated
  using (doctor_id = auth.uid()) with check (doctor_id = auth.uid());

-- Additive policies: existing patient policies remain in place.
drop policy if exists care_nest_doctor_shared_records on public.medical_records;
create policy care_nest_doctor_shared_records on public.medical_records for select to authenticated
  using (public.carenest_can_access_patient(patient_id));
drop policy if exists care_nest_doctor_shared_metrics on public.health_metrics;
create policy care_nest_doctor_shared_metrics on public.health_metrics for select to authenticated
  using (public.carenest_can_access_patient(patient_id));
drop policy if exists care_nest_doctor_find_shared_patients on public.profiles;
create policy care_nest_doctor_find_shared_patients on public.profiles for select to authenticated
  using (id = auth.uid() or role = 'doctor' or public.carenest_can_access_patient(id));
drop policy if exists care_nest_doctor_assigned_appointments on public.appointments;
create policy care_nest_doctor_assigned_appointments on public.appointments for select to authenticated
  using (doctor_id = auth.uid());
drop policy if exists care_nest_doctor_update_appointments on public.appointments;
create policy care_nest_doctor_update_appointments on public.appointments for update to authenticated
  using (doctor_id = auth.uid()) with check (doctor_id = auth.uid());
