-- Smart Health Record: non-destructive baseline schema and RLS
create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, full_name text not null default '', role text not null default 'patient' check (role in ('patient','doctor','admin')), created_at timestamptz not null default now());
create table if not exists public.medical_records (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, title text not null, file_path text not null, file_type text, created_at timestamptz not null default now());
create table if not exists public.health_metrics (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, metric_type text not null, value numeric not null, unit text not null, measured_at timestamptz not null default now(), notes text);
create table if not exists public.medicines (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, name text not null, dosage text, frequency text, start_date date, end_date date, notes text, created_at timestamptz not null default now());
create table if not exists public.appointments (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, doctor_id uuid references public.profiles(id), scheduled_at timestamptz not null, reason text, status text not null default 'scheduled' check (status in ('scheduled','completed','cancelled')), created_at timestamptz not null default now());
create table if not exists public.record_sharing (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, doctor_id uuid not null references public.profiles(id) on delete cascade, expires_at timestamptz, created_at timestamptz not null default now(), unique(patient_id, doctor_id));
create table if not exists public.ai_reports (id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.profiles(id) on delete cascade, report_text text not null, created_at timestamptz not null default now());

-- Create profile for new auth users; role is always patient on self-registration.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id,email,full_name) values (new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict (id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.medical_records enable row level security; alter table public.health_metrics enable row level security; alter table public.medicines enable row level security; alter table public.appointments enable row level security; alter table public.record_sharing enable row level security; alter table public.ai_reports enable row level security;

drop policy if exists "profile self read" on profiles; drop policy if exists "profile self update" on profiles; drop policy if exists "records access" on medical_records; drop policy if exists "records patient write" on medical_records; drop policy if exists "records patient delete" on medical_records; drop policy if exists "metrics access" on health_metrics; drop policy if exists "metrics patient write" on health_metrics; drop policy if exists "metrics patient delete" on health_metrics; drop policy if exists "medicines access" on medicines; drop policy if exists "medicines patient write" on medicines; drop policy if exists "appointments access" on appointments; drop policy if exists "appointments patient write" on appointments; drop policy if exists "sharing patient manage" on record_sharing; drop policy if exists "reports access" on ai_reports; drop policy if exists "reports patient write" on ai_reports;

create or replace function public.can_access_patient(pid uuid) returns boolean language sql stable security definer set search_path=public as $$ select auth.uid() = pid or exists (select 1 from record_sharing s where s.patient_id=pid and s.doctor_id=auth.uid() and (s.expires_at is null or s.expires_at > now())) $$;

create policy "profile self read" on profiles for select using (id=auth.uid() or (role='doctor' and exists(select 1 from record_sharing s where s.patient_id=profiles.id and s.doctor_id=auth.uid())));
create policy "profile self update" on profiles for update using (id=auth.uid()) with check (id=auth.uid() and role='patient');
create policy "records access" on medical_records for select using (can_access_patient(patient_id)); create policy "records patient write" on medical_records for insert with check (patient_id=auth.uid()); create policy "records patient delete" on medical_records for delete using (patient_id=auth.uid());
create policy "metrics access" on health_metrics for select using (can_access_patient(patient_id)); create policy "metrics patient write" on health_metrics for insert with check (patient_id=auth.uid()); create policy "metrics patient delete" on health_metrics for delete using (patient_id=auth.uid());
create policy "medicines access" on medicines for select using (can_access_patient(patient_id)); create policy "medicines patient write" on medicines for insert with check (patient_id=auth.uid()); create policy "appointments access" on appointments for select using (patient_id=auth.uid() or doctor_id=auth.uid()); create policy "appointments patient write" on appointments for insert with check (patient_id=auth.uid());
create policy "sharing patient manage" on record_sharing for all using (patient_id=auth.uid()) with check (patient_id=auth.uid()); create policy "reports access" on ai_reports for select using (can_access_patient(patient_id)); create policy "reports patient write" on ai_reports for insert with check (patient_id=auth.uid());

insert into storage.buckets (id,name,public) values ('medical-records','medical-records',false) on conflict (id) do nothing;
drop policy if exists "private uploads" on storage.objects; drop policy if exists "private downloads" on storage.objects;
create policy "private uploads" on storage.objects for insert to authenticated with check (bucket_id='medical-records' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "private downloads" on storage.objects for select to authenticated using (bucket_id='medical-records' and ((storage.foldername(name))[1]=auth.uid()::text or public.can_access_patient(((storage.foldername(name))[1])::uuid)));
