<?php
declare(strict_types=1);
function require_admin(): void { require_role('admin'); }
function admin_h(mixed $v): string { return htmlspecialchars((string)($v ?? ''),ENT_QUOTES,'UTF-8'); }
function admin_portal(): void {
 require_admin(); $sb=new Supabase(); $page=(string)($_GET['page']??'admin_dashboard'); $adminId=(string)user()['id'];
 $tabs=['admin_dashboard'=>'Overview','admin_verification'=>'Doctor verification','admin_users'=>'Users','admin_appointments'=>'Appointments','admin_announcements'=>'Announcements','admin_audit'=>'Audit log','admin_export'=>'Exports']; if(!isset($tabs[$page]))$page='admin_dashboard';
 if($_SERVER['REQUEST_METHOD']==='POST'){try{$form=(string)($_POST['form']??'');
  if($form==='review_doctor'){$id=(string)($_POST['doctor_id']??'');if(!preg_match('/^[0-9a-f-]{36}$/i',$id))throw new RuntimeException('Invalid doctor selected.');$sb->rpc('carenest_set_doctor_verification',['target_doctor'=>$id,'next_status'=>(string)$_POST['verification_status'],'review_reason'=>trim((string)$_POST['verification_reason'])]);flash('success','Verification updated and the doctor was notified.');}
  elseif($form==='account_status'){$id=(string)($_POST['user_id']??'');if(!preg_match('/^[0-9a-f-]{36}$/i',$id))throw new RuntimeException('Invalid user selected.');$sb->rpc('carenest_set_account_status',['target_user'=>$id,'next_status'=>(string)$_POST['account_status'],'reason'=>trim((string)$_POST['reason'])]);flash('success','Account status updated.');}
  elseif($form==='announcement'){$target=trim((string)($_POST['target_user']??''));$sb->rpc('carenest_admin_announcement',['target_user'=>$target===''?null:$target,'audience'=>(string)$_POST['audience'],'announcement_title'=>trim((string)$_POST['title']),'announcement_body'=>trim((string)$_POST['body'])]);flash('success','In-app announcement sent.');}
 }catch(Throwable $e){flash('danger',safe_error_message($e));}redirect('?page='.urlencode($_POST['return_page']??$page));}
 if($page==='admin_export'){$kind=(string)($_GET['kind']??'users');$rows=$kind==='appointments'?$sb->db('GET','appointments','?select=id,patient_id,doctor_id,status,scheduled_at,reason,created_at&order=created_at.desc'):$sb->db('GET','profiles','?select=id,full_name,email,role,account_status,verification_status,created_at&order=created_at.desc');$sb->rpc('carenest_audit',['event_action'=>'export_'.$kind,'target_kind'=>'export','target_value'=>null,'event_details'=>['rows'=>count($rows)]]);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="carenest-'.$kind.'-'.date('Ymd').'.csv"');$o=fopen('php://output','w');if($rows){fputcsv($o,array_keys($rows[0]));foreach($rows as $row)fputcsv($o,$row);}fclose($o);exit;}
 try { $profiles=$sb->db('GET','profiles','?select=id,full_name,email,role,account_status,verification_status,verification_reason,credential_path,created_at&order=created_at.desc'); }
 catch(Throwable $e) { flash('warning','Administrator features are being set up. Run the administrator governance migration in Supabase, then sign in again.'); redirect('?page=login&role=admin'); }
 $doctors=array_values(array_filter($profiles,fn($p)=>($p['role']??'')==='doctor'));head('Administrator · '.$tabs[$page]); ?>
<div class="admin-shell"><div class="d-flex justify-content-between align-items-center mb-4"><div><span class="eyebrow">Restricted area</span><h1 class="h3 mb-0">CareNest administration</h1></div><span class="role-chip">Administrator only</span></div><nav class="nav nav-pills gap-2 mb-4"><?php foreach($tabs as $k=>$label): ?><a class="nav-link <?=$page===$k?'active':''?>" href="?page=<?=$k?>"><?=admin_h($label)?></a><?php endforeach ?></nav>
<?php if($page==='admin_dashboard'): $a=$sb->db('GET','appointments','?select=id,status&limit=1000');$r=$sb->db('GET','medical_records','?select=id&limit=1000');$verified=count(array_filter($doctors,fn($d)=>($d['verification_status']??'')==='verified'));?><div class="row g-3"><div class="col-md-3"><div class="card p-3"><small>Patients</small><div class="metric"><?=count(array_filter($profiles,fn($p)=>($p['role']??'')==='patient'))?></div></div></div><div class="col-md-3"><div class="card p-3"><small>Doctors</small><div class="metric"><?=count($doctors)?></div><small><?=$verified?> verified</small></div></div><div class="col-md-3"><div class="card p-3"><small>Appointments</small><div class="metric"><?=count($a)?></div></div></div><div class="col-md-3"><div class="card p-3"><small>Record uploads</small><div class="metric"><?=count($r)?></div></div></div></div>
<?php elseif($page==='admin_verification'): ?><div class="card p-4"><h2 class="h5">Doctor verification</h2><?php if(!$doctors): ?><p class="text-muted">No doctor profiles yet.</p><?php endif;foreach($doctors as $d):?><div class="border rounded-4 p-3 mb-3"><strong><?=admin_h($d['full_name'])?></strong><div class="small text-muted"><?=admin_h($d['email'])?> · <?=admin_h($d['verification_status']??'verification_required')?></div><?php if(!empty($d['credential_path'])):?><a class="small" href="?action=credential_download&doctor_id=<?=urlencode($d['id'])?>">Open credential document</a><?php endif?><form method="post" class="row g-2 mt-2"><input type="hidden" name="form" value="review_doctor"><input type="hidden" name="return_page" value="admin_verification"><input type="hidden" name="doctor_id" value="<?=admin_h($d['id'])?>"><div class="col-md-3"><select class="form-select form-select-sm" name="verification_status"><?php foreach(['verification_required','pending','under_review','verified','rejected'] as $s):?><option <?=$s===($d['verification_status']??'')?'selected':''?>><?=admin_h(str_replace('_',' ',$s))?></option><?php endforeach?></select></div><div class="col-md-6"><input class="form-control form-control-sm" name="verification_reason" placeholder="Reason" value="<?=admin_h($d['verification_reason'])?>"></div><div class="col-md-3"><button class="btn btn-sm btn-primary w-100">Confirm change</button></div></form></div><?php endforeach?></div>
<?php elseif($page==='admin_users'): ?><div class="card p-4"><h2 class="h5">User management</h2><div class="table-responsive"><table class="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($profiles as $p):?><tr><td><?=admin_h($p['full_name'])?><div class="small text-muted"><?=admin_h($p['email'])?></div></td><td><?=admin_h($p['role'])?></td><td><?=admin_h($p['account_status']??'active')?></td><td><?php if($p['id']!==$adminId):?><form method="post" class="d-flex gap-2"><input type="hidden" name="form" value="account_status"><input type="hidden" name="return_page" value="admin_users"><input type="hidden" name="user_id" value="<?=admin_h($p['id'])?>"><input type="hidden" name="account_status" value="<?=($p['account_status']??'active')==='suspended'?'active':'suspended'?>"><input class="form-control form-control-sm" name="reason" placeholder="Reason"><button class="btn btn-sm btn-outline-primary"><?=($p['account_status']??'active')==='suspended'?'Reactivate':'Suspend'?></button></form><?php else:?><span class="small text-muted">Your account</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></div>
<?php elseif($page==='admin_appointments'): $items=$sb->db('GET','appointments','?select=id,patient_id,doctor_id,status,scheduled_at,reason,created_at&order=created_at.desc&limit=200');?><div class="card p-4"><h2 class="h5">Appointment oversight</h2><div class="table-responsive"><table class="table"><thead><tr><th>Status</th><th>When</th><th>Patient</th><th>Doctor</th><th>Reason</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?=admin_h($i['status'])?></td><td><?=admin_h($i['scheduled_at'])?></td><td><?=admin_h($i['patient_id'])?></td><td><?=admin_h($i['doctor_id'])?></td><td><?=admin_h($i['reason'])?></td></tr><?php endforeach?></tbody></table></div></div>
<?php elseif($page==='admin_announcements'):?><div class="card p-4"><h2 class="h5">In-app announcement</h2><form method="post" class="row g-3"><input type="hidden" name="form" value="announcement"><input type="hidden" name="return_page" value="admin_announcements"><div class="col-md-4"><select class="form-select" name="audience"><option value="patients">All patients</option><option value="doctors">All doctors</option><option value="specific">Specific user ID</option></select></div><div class="col-md-8"><input class="form-control" name="target_user" placeholder="User UUID for a specific user"></div><div class="col-md-6"><input class="form-control" name="title" placeholder="Title" required></div><div class="col-md-6"><input class="form-control" name="body" placeholder="Message" required></div><div><button class="btn btn-primary">Confirm and send</button></div></form></div>
<?php elseif($page==='admin_audit'): $logs=$sb->db('GET','audit_logs','?select=*&order=created_at.desc&limit=200');?><div class="card p-4"><h2 class="h5">Audit log</h2><?php if(!$logs):?><p class="text-muted">No admin actions recorded yet.</p><?php endif;foreach($logs as $l):?><div class="border-bottom py-2"><strong><?=admin_h($l['action'])?></strong><span class="small text-muted"> <?=admin_h($l['target_type'])?> · <?=admin_h($l['target_id'])?> · <?=admin_h($l['created_at'])?></span></div><?php endforeach?></div>
<?php else:?><div class="card p-4"><h2 class="h5">CSV exports</h2><p class="text-muted">Administrative data only; medical content is never included.</p><a class="btn btn-outline-primary me-2" href="?page=admin_export&kind=users">Users CSV</a><a class="btn btn-outline-primary" href="?page=admin_export&kind=appointments">Appointments CSV</a></div><?php endif?></div><?php foot();
}
