<?php
declare(strict_types=1);

/** Escapes nullable text and numeric values returned by Supabase without type errors. */
function h(mixed $value): string { return htmlspecialchars($value === null ? '' : (string)$value, ENT_QUOTES, 'UTF-8'); }
function doctor_nav(string $active): array {
    return [
        'doctor_dashboard'=>'Overview', 'doctor_patients'=>'My patients', 'doctor_records'=>'Shared records',
        'doctor_appointments'=>'Appointments', 'doctor_notes'=>'Clinical notes', 'doctor_profile'=>'My profile',
        'doctor_verification'=>'Verification', 'doctor_security'=>'Security',
    ];
}
function doctor_patient_access(Supabase $sb, string $doctorId, string $patientId): bool {
    $rows=$sb->db('GET','record_sharing','?select=id,expires_at&doctor_id=eq.'.rawurlencode($doctorId).'&patient_id=eq.'.rawurlencode($patientId).'&status=eq.active&limit=1');
    return !empty($rows) && (empty($rows[0]['expires_at']) || strtotime((string)$rows[0]['expires_at']) > time());
}
function doctor_portal(): void {
    require_role('doctor');
    $sb=new Supabase(); $doctorId=(string)user()['id'];
    $page=$_GET['page'] ?? 'doctor_dashboard';
    $allowed=array_keys(doctor_nav(''));
    if (!in_array($page,$allowed,true)) $page='doctor_dashboard';
    if ($_SERVER['REQUEST_METHOD']==='POST') {
        $form=$_POST['form'] ?? '';
        try {
            if ($form==='password_change') {
                change_password((string)($_POST['current_password'] ?? ''),(string)($_POST['new_password'] ?? ''),(string)($_POST['confirm_password'] ?? ''));
                flash('success','Password changed. Please sign in again.'); redirect('?page=login');
            }
            if ($form==='doctor_profile') {
                $specializations=['General Physician','Cardiologist','Dermatologist','Orthopedic Specialist','Gynecologist / Obstetrician','Pediatrician','Neurologist','Dentist','Ophthalmologist','ENT Specialist','Psychiatrist','Radiologist','General Surgeon','Other'];
                $specialization=in_array($_POST['specialization'] ?? '',$specializations,true) ? $_POST['specialization'] : 'Other';
                $sb->db('PATCH','profiles','?id=eq.'.rawurlencode($doctorId), ['full_name'=>trim($_POST['full_name'] ?? ''),'phone'=>trim($_POST['phone'] ?? ''),'address'=>trim($_POST['address'] ?? ''),'professional_title'=>trim($_POST['professional_title'] ?? ''),'specialization'=>$specialization,'specialization_other'=>trim($_POST['specialization_other'] ?? ''),'clinic_name'=>trim($_POST['clinic_name'] ?? ''),'qualification'=>trim($_POST['qualification'] ?? ''),'license_number'=>trim($_POST['license_number'] ?? '')]);
                profile(true); flash('success','Your clinician profile was updated.');
            }
            if ($form==='doctor_credential') {
                $upload=validated_medical_upload($_FILES['credential'] ?? []);
                $path=$doctorId.'/credentials/'.bin2hex(random_bytes(16)).'.'.$upload['extension'];
                $sb->storageUpload($path,(string)file_get_contents($upload['tmp_name']),$upload['mime']);
                $sb->db('PATCH','profiles','?id=eq.'.rawurlencode($doctorId),['credential_path'=>$path,'credential_document_type'=>trim((string)($_POST['credential_document_type'] ?? 'Professional credential')),'credential_number'=>trim((string)($_POST['credential_number'] ?? '')),'issuing_institution'=>trim((string)($_POST['issuing_institution'] ?? ''))]);
                profile(true); flash('success','Credential document submitted for administrator review.');
            }
            if ($form==='note') {
                $patientId=(string)($_POST['patient_id'] ?? '');
                if (!doctor_patient_access($sb,$doctorId,$patientId)) throw new RuntimeException('This patient has not shared access with you.');
                $noteText=trim($_POST['note_text'] ?? '');
                if (mb_strlen($noteText) < 5 || mb_strlen($noteText) > 5000) throw new RuntimeException('Please enter a clinical note between 5 and 5,000 characters.');
                $sb->db('POST','doctor_notes','', [[
                    'doctor_id'=>$doctorId,'patient_id'=>$patientId,'diagnosis'=>trim($_POST['diagnosis'] ?? ''),
                    'treatment_plan'=>trim($_POST['treatment_plan'] ?? ''),'note_type'=>trim($_POST['note_type'] ?? 'Clinical note'),'note_text'=>$noteText
                ]]); flash('success','Clinical note saved securely.');
            }
            if ($form==='appointment_status') {
                $id=(string)($_POST['id'] ?? '');
                $sb->db('PATCH','appointments','?id=eq.'.rawurlencode($id).'&doctor_id=eq.'.rawurlencode($doctorId), ['status'=>$_POST['status'] ?? 'scheduled']);
                flash('success','Appointment status updated.');
            }
        } catch(Throwable $e) { flash('danger',safe_error_message($e)); }
        redirect('?page='.urlencode($_POST['return_page'] ?? $page));
    }
    $profile=profile() ?? []; $nav=doctor_nav($page);
    if ($page === 'doctor_verification') {
        head('Credential verification');
        $status=(string)($profile['verification_status'] ?? 'pending'); ?>
        <div class="container py-5"><div class="card doctor-card p-4 mx-auto" style="max-width:720px"><span class="tag"><?=$status === 'verified' ? '✓ VERIFIED CLINICIAN' : '◷ '.strtoupper(h($status))?></span><h1 class="h3 mt-3">Credential verification</h1><p class="text-muted"><?=$status === 'verified' ? 'Your professional credentials have been approved by a reviewer.' : 'A credential upload is not automatic approval. Complete your professional profile and submit documents for a reviewer to assess.'?></p><?php if($status !== 'verified'): ?><form method="post" enctype="multipart/form-data" class="row g-3 border-top pt-3"><input type="hidden" name="form" value="doctor_credential"><input type="hidden" name="return_page" value="doctor_verification"><div class="col-md-6"><label class="form-label">Credential document</label><input class="form-control" type="file" name="credential" accept="application/pdf,image/jpeg,image/png,image/webp" required></div><div class="col-md-6"><label class="form-label">Document type</label><input class="form-control" name="credential_document_type" placeholder="Licence / degree / certificate" required></div><div class="col-md-6"><label class="form-label">Document number</label><input class="form-control" name="credential_number"></div><div class="col-md-6"><label class="form-label">Issuing institution</label><input class="form-control" name="issuing_institution"></div><div><button class="btn btn-primary">Submit for review</button></div></form><?php endif ?></div></div><?php foot(); return;
    }
    if ($page === 'doctor_profile') {
        $specialties=['General Physician','Cardiologist','Dermatologist','Orthopedic Specialist','Gynecologist / Obstetrician','Pediatrician','Neurologist','Dentist','Ophthalmologist','ENT Specialist','Psychiatrist','Radiologist','General Surgeon','Other'];
        head('Doctor profile'); ?>
        <div class="container py-5"><div class="card doctor-card p-4 mx-auto" style="max-width:900px"><div class="d-flex justify-content-between align-items-start mb-4"><div><span class="tag"><?=($profile['verification_status'] ?? 'pending') === 'verified' ? '✓ VERIFIED CLINICIAN' : '◷ VERIFICATION PENDING'?></span><h1 class="h3 mt-3 mb-1"><?=h($profile['full_name'] ?? 'Doctor')?></h1><p class="text-muted mb-0"><?=h($profile['specialization'] ?? 'Complete professional profile')?></p></div><a class="btn btn-sm btn-outline-primary" href="?page=doctor_verification">Verification</a></div><form method="post" class="row g-3"><input type="hidden" name="form" value="doctor_profile"><input type="hidden" name="return_page" value="doctor_profile"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" name="full_name" value="<?=h($profile['full_name'] ?? '')?>" required></div><div class="col-md-3"><label class="form-label">Professional title</label><input class="form-control" name="professional_title" value="<?=h($profile['professional_title'] ?? '')?>" placeholder="Dr."></div><div class="col-md-3"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?=h($profile['phone'] ?? '')?>"></div><div class="col-md-6"><label class="form-label">Specialization</label><select class="form-select" name="specialization"><?php foreach($specialties as $s): ?><option <?=$s===($profile['specialization'] ?? '')?'selected':''?>><?=h($s)?></option><?php endforeach ?></select></div><div class="col-md-6"><label class="form-label">Other specialization</label><input class="form-control" name="specialization_other" value="<?=h($profile['specialization_other'] ?? '')?>"></div><div class="col-md-6"><label class="form-label">Clinic / hospital</label><input class="form-control" name="clinic_name" value="<?=h($profile['clinic_name'] ?? '')?>"></div><div class="col-md-6"><label class="form-label">Qualification</label><input class="form-control" name="qualification" value="<?=h($profile['qualification'] ?? '')?>"></div><div class="col-md-6"><label class="form-label">Registration / licence number</label><input class="form-control" name="license_number" value="<?=h($profile['license_number'] ?? '')?>"></div><div class="col-md-6"><label class="form-label">Clinic address</label><input class="form-control" name="address" value="<?=h($profile['address'] ?? '')?>"></div><div class="col-12"><button class="btn btn-primary">Save professional profile</button></div></form></div></div><?php foot(); return;
    }
    head('Clinician portal · '.($nav[$page] ?? 'CareNest')); ?>
<style>
.clinician-shell{min-height:100vh;background:linear-gradient(135deg,#eff7ff,#f7fbff 48%,#eaf8f5)}
.clinician-top{background:#102f46;color:#fff;padding:18px 0}.doctor-mark{display:inline-grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#4ec2b6;color:#fff;font-weight:800;margin-right:10px}.doctor-side{background:#fff;border:1px solid #dbe8ef;border-radius:22px;padding:16px;box-shadow:0 18px 45px rgba(16,47,70,.08);position:sticky;top:20px}.doctor-side a{display:block;padding:12px 14px;border-radius:12px;color:#365264;text-decoration:none;font-weight:600;margin:3px 0}.doctor-side a.active,.doctor-side a:hover{background:#102f46;color:#fff}.doctor-card{border:0;border-radius:20px;box-shadow:0 12px 30px rgba(16,47,70,.08)}.doctor-stat{background:#fff;border-radius:18px;padding:22px;border-left:5px solid #4ec2b6}.tag{font-size:.78rem;padding:5px 10px;background:#e8f7f4;color:#19796f;border-radius:50px;font-weight:700}.patient-row{border:1px solid #e2edf1;border-radius:16px;padding:16px;background:#fff;margin-bottom:12px}
</style>
<div class="clinician-shell"><header class="clinician-top"><div class="container d-flex align-items-center justify-content-between"><a class="text-white text-decoration-none fs-4 fw-bold" href="?page=doctor_dashboard"><span class="doctor-mark">+</span>CareNest <small class="fs-6 fw-normal opacity-75">Clinician</small></a><div class="d-flex align-items-center gap-3"><span class="d-none d-md-inline">Dr. <?=h($profile['full_name'] ?? 'Clinician')?></span><a class="btn btn-sm btn-outline-light" href="?action=logout">Sign out</a></div></div></header>
<main class="container py-4 py-md-5"><div class="row g-4"><aside class="col-lg-3"><nav class="doctor-side"><div class="px-2 pt-2 pb-3"><span class="tag"><?=($profile['verification_status'] ?? 'pending') === 'verified' ? '✓ VERIFIED CLINICIAN' : '◷ '.strtoupper(str_replace('_',' ',(string)($profile['verification_status'] ?? 'pending')))?></span><div class="fw-bold mt-2"><?=h($profile['full_name'] ?? 'Doctor')?></div><div class="small text-muted"><?=h($profile['specialization'] ?? 'Professional profile incomplete')?></div></div><?php foreach($nav as $key=>$name): ?><a class="<?=$page===$key?'active':''?>" href="?page=<?=$key?>"><?=$name?></a><?php endforeach ?></nav></aside><section class="col-lg-9">
<?php if($page==='doctor_dashboard'):
    $shares=$sb->db('GET','record_sharing','?select=patient_id,shared_at,expires_at&doctor_id=eq.'.rawurlencode($doctorId).'&status=eq.active');
    $appointments=$sb->db('GET','appointments','?select=*&doctor_id=eq.'.rawurlencode($doctorId).'&order=scheduled_at.asc&limit=5'); ?>
    <span class="text-uppercase small fw-bold text-success">Clinician workspace</span><h1 class="display-6 fw-bold mt-2">Good day, Dr. <?=h(explode(' ',trim($profile['full_name'] ?? 'Doctor'))[0])?>.</h1><p class="text-muted mb-4">Review only the records that patients have explicitly shared with you.</p>
    <div class="row g-3 mb-4"><div class="col-md-6"><div class="doctor-stat"><div class="text-muted small">PATIENTS WITH ACTIVE ACCESS</div><div class="display-6 fw-bold"><?=count($shares)?></div></div></div><div class="col-md-6"><div class="doctor-stat"><div class="text-muted small">UPCOMING APPOINTMENTS</div><div class="display-6 fw-bold"><?=count($appointments)?></div></div></div></div>
    <div class="card doctor-card p-4"><div class="d-flex justify-content-between"><h2 class="h5">Upcoming appointments</h2><a href="?page=doctor_appointments">View all</a></div><?php if(!$appointments): ?><p class="text-muted mb-0">No appointments are assigned to you yet.</p><?php endif; foreach($appointments as $a): ?><div class="border-top pt-3 mt-3"><strong><?=h($a['reason'] ?? 'Patient appointment')?></strong><span class="ms-2 tag"><?=h($a['status'] ?? 'scheduled')?></span><div class="small text-muted mt-1"><?=h($a['scheduled_at'] ?? '')?></div></div><?php endforeach ?></div>
<?php elseif($page==='doctor_patients'):
    $shares=$sb->db('GET','record_sharing','?select=patient_id,shared_at,expires_at&doctor_id=eq.'.rawurlencode($doctorId).'&status=eq.active&order=shared_at.desc'); ?>
    <span class="text-uppercase small fw-bold text-success">Consent-based access</span><h1 class="display-6 fw-bold mt-2">My patients</h1><p class="text-muted">These people granted you access. You cannot browse any other patient data.</p>
    <?php if(!$shares): ?><div class="card doctor-card p-4 text-muted">No patient has shared records with you yet. Ask the patient to use “Share with doctor” and enter your registered email.</div><?php endif; foreach($shares as $share): $people=$sb->db('GET','profiles','?select=full_name,email,blood_group,allergies&id=eq.'.rawurlencode($share['patient_id']).'&limit=1'); $person=$people[0]??[]; ?><div class="patient-row"><div class="d-flex justify-content-between align-items-start"><div><strong><?=h($person['full_name'] ?? 'Patient')?></strong><div class="small text-muted"><?=h($person['email'] ?? '')?></div><div class="small mt-2">Blood group: <?=h($person['blood_group'] ?? 'Not recorded')?> · Allergies: <?=h($person['allergies'] ?? 'Not recorded')?></div></div><a class="btn btn-sm btn-primary" href="?page=doctor_records&patient_id=<?=urlencode($share['patient_id'])?>">Open shared record</a></div></div><?php endforeach ?>
<?php elseif($page==='doctor_records'):
    $patientId=(string)($_GET['patient_id'] ?? ''); if(!$patientId || !doctor_patient_access($sb,$doctorId,$patientId)): ?><div class="alert alert-warning">Choose a patient from <a href="?page=doctor_patients">My patients</a>. Access is required before records can be shown.</div><?php else: $people=$sb->db('GET','profiles','?select=full_name,email,blood_group,allergies&id=eq.'.rawurlencode($patientId).'&limit=1');$person=$people[0]??[];$records=$sb->db('GET','medical_records','?select=*&patient_id=eq.'.rawurlencode($patientId).'&order=created_at.desc');$metrics=$sb->db('GET','health_metrics','?select=*&patient_id=eq.'.rawurlencode($patientId).'&order=measured_at.desc&limit=8'); ?>
<a class="small" href="?page=doctor_patients">← My patients</a><h1 class="display-6 fw-bold mt-2"><?=h($person['full_name'] ?? 'Patient')?>’s shared health record</h1><div class="card doctor-card p-4 mb-4"><strong>Safety information</strong><div class="mt-2">Blood group: <?=h($person['blood_group'] ?? 'Not recorded')?> · Allergies: <?=h($person['allergies'] ?? 'Not recorded')?></div></div><div class="row g-3"><div class="col-md-6"><div class="card doctor-card p-4 h-100"><h2 class="h5">Documents</h2><?php if(!$records): ?><p class="text-muted">No documents shared.</p><?php endif; foreach($records as $r): ?><div class="border-top pt-2 mt-2"><strong><?=h($r['title'] ?? $r['record_title'] ?? 'Medical record')?></strong><div class="small text-muted"><?=h($r['created_at'] ?? '')?></div></div><?php endforeach ?></div></div><div class="col-md-6"><div class="card doctor-card p-4 h-100"><h2 class="h5">Recent vitals</h2><?php if(!$metrics): ?><p class="text-muted">No measurements shared.</p><?php endif; foreach($metrics as $m): ?><div class="border-top pt-2 mt-2"><strong><?=h($m['metric_type'] ?? '')?>: <?=h($m['value'] ?? $m['metric_value'] ?? '')?> <?=h($m['unit'] ?? '')?></strong><div class="small text-muted"><?=h($m['measured_at'] ?? $m['recorded_at'] ?? '')?></div></div><?php endforeach ?></div></div></div><a class="btn btn-primary mt-4" href="?page=doctor_notes&patient_id=<?=urlencode($patientId)?>">Add clinical note</a><?php endif ?>
<?php elseif($page==='doctor_appointments'):
    $items=$sb->db('GET','appointments','?select=*&doctor_id=eq.'.rawurlencode($doctorId).'&order=scheduled_at.asc'); ?><h1 class="display-6 fw-bold">Appointments</h1><p class="text-muted">Update only appointments assigned to your account.</p><?php if(!$items): ?><div class="card doctor-card p-4 text-muted">There are no assigned appointments.</div><?php endif; foreach($items as $a): ?><div class="patient-row"><strong><?=h($a['reason'] ?? 'Appointment')?></strong><div class="small text-muted mb-2"><?=h($a['scheduled_at'] ?? '')?></div><form method="post" class="d-flex gap-2"><input type="hidden" name="form" value="appointment_status"><input type="hidden" name="return_page" value="doctor_appointments"><input type="hidden" name="id" value="<?=h($a['id'])?>"><select class="form-select form-select-sm" name="status" style="max-width:180px"><?php foreach(['scheduled','confirmed','completed','cancelled'] as $status): ?><option <?=$status===($a['status']??'')?'selected':''?>><?=$status?></option><?php endforeach ?></select><button class="btn btn-sm btn-primary">Save</button></form></div><?php endforeach ?>
<?php elseif($page==='doctor_notes'):
    $patientId=(string)($_GET['patient_id'] ?? ''); $can=$patientId && doctor_patient_access($sb,$doctorId,$patientId); $notes=$sb->db('GET','doctor_notes','?select=*&doctor_id=eq.'.rawurlencode($doctorId).'&order=created_at.desc&limit=20'); ?><h1 class="display-6 fw-bold">Clinical notes</h1><?php if($can): ?><div class="card doctor-card p-4 mb-4"><h2 class="h5">New note</h2><form method="post" class="row g-3"><input type="hidden" name="form" value="note"><input type="hidden" name="return_page" value="doctor_notes"><input type="hidden" name="patient_id" value="<?=h($patientId)?>"><div class="col-md-6"><input class="form-control" name="diagnosis" placeholder="Diagnosis / clinical impression"></div><div class="col-md-6"><input class="form-control" name="treatment_plan" placeholder="Treatment plan"></div><div class="col-12"><textarea class="form-control" rows="4" name="note_text" placeholder="Private clinical note" required></textarea></div><div><button class="btn btn-primary">Save note</button></div></form></div><?php else: ?><div class="alert alert-info">Open a shared patient record first to add a note.</div><?php endif; foreach($notes as $note): ?><div class="patient-row"><strong><?=h($note['diagnosis'] ?: 'Clinical note')?></strong><div class="mt-2"><?=nl2br(h($note['note_text']))?></div><div class="small text-muted mt-2"><?=h($note['created_at'])?></div></div><?php endforeach ?>
<?php elseif($page==='doctor_profile'): ?><h1 class="display-6 fw-bold">My clinician profile</h1><div class="card doctor-card p-4"><form method="post" class="row g-3"><input type="hidden" name="form" value="doctor_profile"><input type="hidden" name="return_page" value="doctor_profile"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" name="full_name" value="<?=h($profile['full_name'] ?? '')?>" required></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?=h($profile['phone'] ?? '')?>"></div><div class="col-12"><label class="form-label">Clinic address</label><input class="form-control" name="address" value="<?=h($profile['address'] ?? '')?>"></div><div><button class="btn btn-primary">Save profile</button></div></form></div>
<?php else: ?><h1 class="display-6 fw-bold">Security</h1><div class="row g-4"><div class="col-lg-7"><div class="card doctor-card p-4"><h2 class="h5">Change password</h2><p class="small text-muted">Confirm your current password before choosing a new one.</p><form method="post" class="row g-3"><input type="hidden" name="form" value="password_change"><input type="hidden" name="return_page" value="doctor_security"><div class="col-12"><input class="form-control" type="password" name="current_password" placeholder="Current password" required></div><div class="col-md-6"><input class="form-control" type="password" name="new_password" placeholder="New password (10+ characters)" minlength="10" required></div><div class="col-md-6"><input class="form-control" type="password" name="confirm_password" placeholder="Confirm new password" minlength="10" required></div><div><button class="btn btn-primary">Update password</button></div></form></div></div><div class="col-lg-5"><div class="card doctor-card p-4 h-100"><h2 class="h5">Protected clinician access</h2><p class="text-muted mb-0">You can only open records that a patient has actively shared with you. Signing out clears this browser session.</p></div></div></div><?php endif ?>
</section></div></main></div><?php foot();
}
